// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://karlo.co.id/terms",
        "contact": {
            "name": "Karlo Engineering",
            "email": "engineering@karlo.co.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Change password",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/check-available/{kind}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Check identifier availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email|username|phone",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Value to check",
                        "name": "value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_services.LoginResult"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout from all devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.User"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_services.TokenPair"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Registration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.User"
                        }
                    }
                }
            }
        },
        "/auth/register-member": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a company member",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.User"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_platform_response.Meta"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update own profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/users/{id}/permission": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Set user permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/users/{id}/suspend": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Suspend or restore user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_karlo_authentication-service_internal_models.Company": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bankAccount": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.JSONMap"
                },
                "bannerUrl": {
                    "type": "string"
                },
                "cityId": {
                    "type": "string"
                },
                "companyProfile": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "emailRecipients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isSuspended": {
                    "type": "boolean"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "legacyId": {
                    "type": "string"
                },
                "logoUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "noSiup": {
                    "type": "string"
                },
                "noTdp": {
                    "type": "string"
                },
                "npwp": {
                    "type": "string"
                },
                "provinceId": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "settings": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.CompanySettings"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_authentication-service_internal_models.CompanySettings": {
            "type": "object",
            "properties": {
                "accessTolls": {
                    "type": "boolean"
                },
                "activeAgreementVerifiedOnly": {
                    "type": "boolean"
                },
                "cancelWithValidate": {
                    "type": "boolean"
                },
                "finishWithGeofencing": {
                    "type": "boolean"
                },
                "maxDriverAvailableAfterOrderDone": {
                    "type": "integer"
                },
                "pph23Percentage": {
                    "type": "number"
                },
                "ppnPercentage": {
                    "type": "number"
                },
                "useStrictAgreement": {
                    "type": "boolean"
                }
            }
        },
        "github_com_karlo_authentication-service_internal_models.JSONMap": {
            "type": "object",
            "additionalProperties": true
        },
        "github_com_karlo_authentication-service_internal_models.Permission": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "type": "boolean"
                }
            }
        },
        "github_com_karlo_authentication-service_internal_models.User": {
            "type": "object",
            "properties": {
                "acceptedTncAt": {
                    "description": "The column tag is explicit: GORM's default naming would derive\n\"accepted_tn_c_at\" from the capital C, which does not exist.",
                    "type": "string"
                },
                "accountType": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "alternativePhones": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.JSONMap"
                },
                "averageRating": {
                    "type": "number"
                },
                "birthDate": {
                    "type": "string"
                },
                "cityId": {
                    "type": "string"
                },
                "company": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.Company"
                },
                "companyId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emergencyContactName": {
                    "type": "string"
                },
                "emergencyContactPhone": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isEmailVerified": {
                    "type": "boolean"
                },
                "isPhoneVerified": {
                    "type": "boolean"
                },
                "isSuspended": {
                    "type": "boolean"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "lastLoginAt": {
                    "type": "string"
                },
                "legacyId": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "permission": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.Permission"
                },
                "phone": {
                    "type": "string"
                },
                "photoUrl": {
                    "type": "string"
                },
                "ratingCount": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_karlo_authentication-service_internal_platform_response.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        },
        "github_com_karlo_authentication-service_internal_services.LoginResult": {
            "type": "object",
            "properties": {
                "tokens": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_services.TokenPair"
                },
                "user": {
                    "$ref": "#/definitions/github_com_karlo_authentication-service_internal_models.User"
                }
            }
        },
        "github_com_karlo_authentication-service_internal_services.TokenPair": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "tokenType": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.loginRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "deviceId": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "username": {
                    "description": "The legacy clients send whichever of these they collected, so all three\nare accepted and folded into one identifier.",
                    "type": "string"
                }
            }
        },
        "internal_handlers.registerRequest": {
            "type": "object",
            "required": [
                "password",
                "role"
            ],
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "RS256 access token issued by the authentication service, as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Karlo Authentication API",
	Description:      "Identity, company membership, sessions, permissions and API keys.\\n\\nThis service is the authority on who a caller is. It signs RS256 tokens with a private key it alone holds; every other service verifies them locally with the public key.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
